version: '3.7'
services:
  mysql:
    image: mysql:5
    container_name: ${PROJECT_NAME}_mysql
    ports:
     - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./dumpdir:/var/backups
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_PASSWORD: root
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    ports: 
      - '8080:80'
  web:
#    image: webdevops/php-apache-dev:7.4 
   #for OJS 3.3 and 3.2
#    image: webdevops/php-apache-dev:7.3
    #for OJS 3.1
    image: webdevops/php-apache-dev:7.2
    #for OJS 3.0 and 2.4
#    image: webdevops/php-apache-dev:5.6

    container_name: ${PROJECT_NAME}_web
    depends_on:
      - mysql
    volumes:
      - "./public_ojs:/app"
#      - "./ojs-3.3.0-7:/app"
#      - "./ojs-3.2.1-4:/app"
      - "./private_ojs:/var/ojs-data/"
    ports:
      - "80:80"
    environment:
      PHP_MEMORY_LIMIT: 512M
      PHP_DISPLAY_ERRORS: 1
#    stdin_open: true
#    tty: true
    links:
      - mysql
